---
title: "Análise preditiva"
author: "Pedro Martins"
date: "22 de agosto de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Análise Preditiva

## Gerando o gráfico de satisfação
```{r}
satisfacao <- read.csv2("satisfacao.csv", sep = ";", header = TRUE)
avaliacao <- as.factor(c("SAT", "INS"))
avaliacao <- lvls_reorder(avaliacao, c(2, 1))

ggplot(data = satisfacao) + 
  geom_point(aes(x = Tempo, y = Preco, color = satisfacao$Classe)) +
  labs(x = "Tempo", y = "Preço") +
  scale_color_manual(values = c("SAT" = "#0F7F1F", "INS" = "#FF0000")) +
  geom_text(aes(x = Tempo + 0.025, y = Preco + 0.03, label = satisfacao$RID)) +
  theme_bw()
```

## Usando o algoritmo kNN

```{r}
library(class)
treinamento <- satisfacao[2:12, 2:3]
rotulos <- satisfacao[2:12, 4:4]
teste <- satisfacao[1:1, 2:3]
estimado <- knn(treinamento, teste, rotulos)
```

## Usando uma rede neural artificial

```{r}
library("RSNNS")
X <- satisfacao[2:3]
Y <- decodeClassLabels(satisfacao[,4])
satisfacao_separada <- splitForTrainingAndTest(X, Y, ratio = 0.10)
satisfacao_normalizada <- normTrainingAndTestSet(satisfacao_separada, dontNormTargets = TRUE, type = "0_1")
modelo_mlp <- mlp(satisfacao_separada$inputsTrain, satisfacao_separada$targetsTrain, size = c(3), maxit = 5000, initFunc = "Randomize_Weights", 
                  learnFunc = "Std_Backpropagation", learnFuncParams = c(0.1), hiddenActFunc = "Act_Logistic", shufflePatterns = TRUE, linOut = TRUE,
                  inputsTest = satisfacao_separada$inputsTest, targetsTest = satisfacao_separada$targetsTest)

```

## Gerando gráfico da curva de aprendizagem

```{r}
plot(modelo_mlp$IterativeFitError, type = 'n', main = "Curva de Aprendizagem", xlab = "Iteração", ylab = "Erro médio quadrado", cex.lab = 1.5, ylim = c(0, 10))
lines(modelo_mlp$IterativeFitError, col = '1', lwd = 3, cex = 2)
lines(modelo_mlp$IterativeTestError, col = '2', lwd = 3)

```

